"""
Django settings for bubblebarter project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-80#g2tvod0t=8o_p762b^=@q#nhc*ef(ynpn0zqnkz&)8n69%l'
# I (luke) have set it in the heroku env, so everyone set locally too
# if 'SECRET_KEY' in os.environ:
#     SECRET_KEY = os.environ["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = True
ALLOWED_HOSTS = ['bubblebarter.herokuapp.com', '*']

# if not IS_HEROKU:
#     DEBUG = True

#ALLOWED_HOSTS = ['bubblebarter.herokuapp.com', '*']
# if IS_HEROKU:
#     ALLOWED_HOSTS = ["*"]
# else:
#     ALLOWED_HOSTS = []


# SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
SENDGRID_API_KEY = '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'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bbapp',
    'django_cas_ng',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]
# 'django_cas_ng.middleware.CASMiddleware'
ROOT_URLCONF = 'bubblebarter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'bbapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bubblebarter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# postgres://zwanybxahhifhl:647449e764fa379b6283962ce984f44707d80118b290e243a2227052df6cdb41@ec2-3-234-204-26.compute-1.amazonaws.com:5432/dcud0ud8iv1g65
# postgres://user:password@host:port/database_name


# import django_heroku
import django_on_heroku
import os

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'd2epjsc1pcidrh',
		'USER': 'utfmbvvowkwczh',
		'PASSWORD': '5c83bb1fc945b2232a2567b0014859fb21701ad3cc00d66fd6b31cbb55faf0c5',
		'HOST': 'ec2-35-169-9-79.compute-1.amazonaws.com',
		'PORT': '5432',
	}
}

# if "DATABASE_URL" in os.environ:
#     # Configure Django for DATABASE_URL environment variable.
#     DATABASES["default"] = dj_database_url.config(
#         conn_max_age=MAX_CONN_AGE, ssl_require=True)


# Optional section to include if
# you want to include static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# By Sarah***
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_cas_ng.backends.CASBackend',
)


#

#----------

CAS_LOGOUT_COMPLETELY = True
CAS_IGNORE_REFERER = True
CAS_SERVER_URL = 'https://fed.princeton.edu/cas/'
CAS_LOGIN_URL ='https://fed.princeton.edu/cas/login'
CAS_LOGIN_URL_NAME = 'cas_ng_login'

CAS_CREATE_USER = True


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#django_heroku.settings(locals())
django_on_heroku.settings(locals()) # this should also handle database_url, allowed_hosts,whitenoise,secret_key (if set), conn_max_age (if set)

# Cloudinary settings
import cloudinary


cloudinary.config( 
  cloud_name = 'dk6iaahrz', 
  api_key = "736282944347261", 
  api_secret = "SJntXN4xjH2Ic2mW74KhyhCnu8o",
  secure = True
)