# Generated by Django 4.1.7 on 2023-03-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('dateexpires', models.DateField()),
                ('dateposted', models.DateField()),
                ('description', models.TextField()),
                ('isactive', models.BooleanField()),
                ('isprivate', models.BooleanField()),
                ('itemid', models.UUIDField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('wants', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposalid', models.UUIDField(primary_key=True, serialize=False)),
                ('dateoffered', models.DateField()),
                ('itembid', models.CharField(max_length=100)),
                ('proposaltext', models.TextField()),
                ('proposedto', models.CharField(max_length=100)),
                ('proposer', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('itemid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('actiontaken', models.CharField(max_length=100)),
                ('reportdate', models.DateField()),
                ('reporteduser', models.CharField(max_length=100)),
                ('reporter', models.CharField(max_length=100)),
                ('reportid', models.UUIDField(primary_key=True, serialize=False)),
                ('reportlink', models.CharField(max_length=100)),
                ('reportstatus', models.CharField(max_length=100)),
                ('reporttext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('netid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('isadmin', models.BooleanField()),
                ('isbanned', models.BooleanField()),
                ('itemsstarred', models.JSONField()),
                ('userbio', models.TextField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
