# Generated by Django 4.1.7 on 2023-03-28 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0002_report_delete_reports_remove_user_isadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 20, 31, 30, 249179, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='itemsstarred',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
