# Generated by Django 4.1.7 on 2023-04-08 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0007_item_image_url_alter_item_dateexpires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 21, 32, 8, 592625, tzinfo=datetime.timezone.utc)),
        ),
    ]
