# Generated by Django 4.1.7 on 2023-04-08 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0008_item_image_public_id_alter_item_dateexpires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 21, 33, 2, 216128, tzinfo=datetime.timezone.utc)),
        ),
    ]
