# Generated by Django 4.1.7 on 2023-04-08 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0009_remove_item_image_url_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 21, 35, 19, 747448, tzinfo=datetime.timezone.utc)),
        ),
    ]
