# Generated by Django 4.1.7 on 2023-04-08 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0013_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 22, 47, 58, 285630, tzinfo=datetime.timezone.utc)),
        ),
    ]
