# Generated by Django 4.1.7 on 2023-04-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0018_alter_item_dateexpires'),
    ]

    operations = [
    ]
