# Generated by Django 4.1.7 on 2023-04-11 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0020_userdetails_alter_item_dateexpires_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 4, 45, 25, 85374, tzinfo=datetime.timezone.utc)),
        ),
    ]
