# Generated by Django 4.1.7 on 2023-04-11 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0021_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='art_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='clothing_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='event_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='food_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='free_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='fun_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='help_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='misc_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='room_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='ticket_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='transport_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='weird_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 19, 22, 45, 434452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='actiontaken',
            field=models.TextField(default=None),
        ),
    ]
