# Generated by Django 4.1.7 on 2023-04-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0022_item_art_tag_item_clothing_tag_item_event_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reportlink',
        ),
        migrations.AddField(
            model_name='report',
            name='reporteditemid',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='report',
            name='reportedproposalid',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 19, 34, 18, 569570, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportstatus',
            field=models.TextField(default='pending', max_length=100),
        ),
    ]
