# Generated by Django 4.1.7 on 2023-04-11 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0023_remove_report_reportlink_report_reporteditemid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 19, 37, 11, 996242, tzinfo=datetime.timezone.utc)),
        ),
    ]
