# Generated by Django 4.1.7 on 2023-04-11 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0024_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 19, 38, 36, 875019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='actiontaken',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporteditemid',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportedproposalid',
            field=models.TextField(default=None, null=True),
        ),
    ]
