# Generated by Django 4.1.7 on 2023-04-20 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0026_remove_item_tags_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='dateupdated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 18, 54, 942093, tzinfo=datetime.timezone.utc)),
        ),
    ]
