# Generated by Django 4.1.7 on 2023-04-20 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0028_alter_item_dateexpires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 17, 28, 37, 479878, tzinfo=datetime.timezone.utc)),
        ),
    ]
