# Generated by Django 4.1.7 on 2023-04-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0030_alter_item_dateexpires_alter_proposal_dateupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dateexpires',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 19, 46, 30, 866303, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporteditemid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
